// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about-me": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about-me" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about-me.tsx": {
    id: "routes/about-me";
    page: "/about-me";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about-me": typeof import("./app/routes/about-me.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};